Add messenger tests to PR template
Sigh. We can't run the tests in CI because of:

    error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/runner/work/nixos-vault-service/nixos-vault-service/messenger/target/debug/deps/libproc_macro_error_attr-5268337e2be2d40f.so)
       --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:284:9
        |
    284 | pub use proc_macro_error_attr::proc_macro_error;
        |         ^^^^^^^^^^^^^^^^^^^^^

    error: could not compile `proc-macro-error` due to previous error